#!/usr/bin/env bash
# Seed all databases with realistic development data.
# Idempotent — safe to run multiple times.
set -euo pipefail

auth()      { docker exec -i infra-auth-db-1      psql -U postgres -d auth_db      "$@"; }
workspace() { docker exec -i infra-workspace-db-1 psql -U postgres -d workspace_db "$@"; }
label()     { docker exec -i infra-label-db-1     psql -U postgres -d label_db     "$@"; }
agent()     { docker exec -i infra-agent-db-1     psql -U postgres -d agent_db     "$@"; }
printdb()   { docker exec -i infra-print-db-1     psql -U postgres -d print_db     "$@"; }

# ─── Fixed UUIDs (stable across re-runs) ──────────────────────────────────────
WS_ID="aaaaaaaa-0000-0000-0000-000000000001"

U_ADMIN="bbbbbbbb-0000-0000-0000-000000000001"
U_OPS="bbbbbbbb-0000-0000-0000-000000000002"
U_VIEW="bbbbbbbb-0000-0000-0000-000000000003"

P_FOOD="cccccccc-0000-0000-0000-000000000001"
P_COSM="cccccccc-0000-0000-0000-000000000002"
P_ELEC="cccccccc-0000-0000-0000-000000000003"

L1="dddddddd-0000-0000-0000-000000000001"  # confirmed food
L2="dddddddd-0000-0000-0000-000000000002"  # confirmed cosmetic
L3="dddddddd-0000-0000-0000-000000000003"  # needs_review electronics
L4="dddddddd-0000-0000-0000-000000000004"  # processing food
L5="dddddddd-0000-0000-0000-000000000005"  # pending

PJ1="eeeeeeee-0000-0000-0000-000000000001"  # ready
PJ2="eeeeeeee-0000-0000-0000-000000000002"  # failed
PJ3="eeeeeeee-0000-0000-0000-000000000003"  # queued

# Password: DevPass123! (bcrypt cost 12, generated by Go's golang.org/x/crypto/bcrypt)
BCRYPT='$2a$12$WW7UAX/WHDLG.BaC1u7h6OjyfCgoYdiVAEDiU0LKmaHsSPtZ//tCe'

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  EtiketAI — seed development data"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ─── auth_db ──────────────────────────────────────────────────────────────────
echo ""
echo "▸ auth_db"
auth <<SQL
INSERT INTO users (id, email, password_hash, is_verified, created_at)
VALUES
  ('$U_ADMIN', 'admin@demo.com',    '$BCRYPT', true, NOW() - INTERVAL '30 days'),
  ('$U_OPS',   'operator@demo.com', '$BCRYPT', true, NOW() - INTERVAL '20 days'),
  ('$U_VIEW',  'viewer@demo.com',   '$BCRYPT', true, NOW() - INTERVAL '10 days')
ON CONFLICT (email) DO NOTHING;
SQL
echo "  ✓ 3 users (admin, operator, viewer)  |  password: DevPass123!"

# ─── workspace_db ─────────────────────────────────────────────────────────────
echo ""
echo "▸ workspace_db"
workspace <<SQL
INSERT INTO workspaces (
    id, name, cui, address, phone,
    plan, label_quota_monthly, label_quota_used,
    created_at, updated_at
) VALUES (
    '$WS_ID', 'Demo Corp SRL', 'RO12345678',
    'Str. Exemplu nr. 1, București', '+40 721 000 001',
    'business', 500, 12,
    NOW() - INTERVAL '30 days', NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO workspace_members (workspace_id, user_id, email, role, invited_at, accepted_at)
VALUES
  ('$WS_ID', '$U_ADMIN', 'admin@demo.com',    'admin',    NOW() - INTERVAL '30 days', NOW() - INTERVAL '30 days'),
  ('$WS_ID', '$U_OPS',   'operator@demo.com', 'operator', NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
  ('$WS_ID', '$U_VIEW',  'viewer@demo.com',   'viewer',   NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days')
ON CONFLICT (workspace_id, user_id) DO NOTHING;
SQL
echo "  ✓ workspace: Demo Corp SRL  |  plan: business  |  quota: 12/500"
echo "  ✓ 3 members: admin, operator, viewer"

# ─── label_db: products ───────────────────────────────────────────────────────
echo ""
echo "▸ label_db — products"
label <<SQL
INSERT INTO products (id, workspace_id, sku, name, category, default_fields, print_count, created_at, updated_at)
VALUES
  (
    '$P_FOOD', '$WS_ID', 'SKU-LAPTE-001', 'Lapte UHT 3.5% Grăsime', 'food',
    '{
      "product_name":      "Lapte UHT 3.5% Grăsime",
      "manufacturer":      "Lactate România SRL",
      "quantity":          "1L",
      "ingredients":       "Lapte integral pasteurizat UHT",
      "country_of_origin": "România"
    }'::jsonb,
    7, NOW() - INTERVAL '25 days', NOW() - INTERVAL '5 days'
  ),
  (
    '$P_COSM', '$WS_ID', 'SKU-CREMA-001', 'Cremă Hidratantă SPF 30', 'cosmetic',
    '{
      "product_name": "Cremă Hidratantă SPF 30",
      "manufacturer": "Beauty Labs SRL",
      "quantity":     "50ml",
      "ingredients":  "Aqua, Glycerin, Zinc Oxide, Titanium Dioxide, Tocopheryl Acetate",
      "warnings":     "A nu se utiliza în apropierea ochilor. A se păstra la loc uscat."
    }'::jsonb,
    3, NOW() - INTERVAL '18 days', NOW() - INTERVAL '3 days'
  ),
  (
    '$P_ELEC', '$WS_ID', 'SKU-HDMI-001', 'Cablu HDMI 4K 2m', 'electronics',
    '{
      "product_name": "Cablu HDMI 4K Ultra HD 2m",
      "manufacturer": "TechConnect SRL",
      "quantity":     "1 buc",
      "warnings":     "A nu se lăsa la îndemâna copiilor mici."
    }'::jsonb,
    1, NOW() - INTERVAL '10 days', NOW()
  )
ON CONFLICT (id) DO NOTHING;
SQL
echo "  ✓ 3 products (Lapte UHT, Cremă SPF30, Cablu HDMI)"

# ─── label_db: labels ─────────────────────────────────────────────────────────
echo ""
echo "▸ label_db — labels"
label <<SQL
-- L1: confirmed food
INSERT INTO labels (id, workspace_id, created_by_user_id, product_id, status, image_s3_key, category, detected_language, fields_translated, compliance_score, confirmed_at, created_at, updated_at)
VALUES (
    '$L1', '$WS_ID', '$U_ADMIN', '$P_FOOD',
    'confirmed', 'labels/$WS_ID/$L1/image.jpg', 'food', 'ro',
    '{
      "product_name":      "Lapte UHT 3.5% Grăsime",
      "manufacturer":      "Lactate România SRL",
      "quantity":          "1L",
      "expiry_date":       "31.12.2026",
      "ingredients":       "Lapte integral pasteurizat UHT",
      "lot_number":        "LOT2026A001",
      "country_of_origin": "România",
      "warnings":          "A se păstra la frigider după deschidere."
    }'::jsonb,
    92,
    NOW() - INTERVAL '22 days', NOW() - INTERVAL '25 days', NOW() - INTERVAL '22 days'
) ON CONFLICT (id) DO NOTHING;

-- L2: confirmed cosmetic
INSERT INTO labels (id, workspace_id, created_by_user_id, product_id, status, image_s3_key, category, detected_language, fields_translated, compliance_score, confirmed_at, created_at, updated_at)
VALUES (
    '$L2', '$WS_ID', '$U_ADMIN', '$P_COSM',
    'confirmed', 'labels/$WS_ID/$L2/image.jpg', 'cosmetic', 'ro',
    '{
      "product_name": "Cremă Hidratantă SPF 30",
      "manufacturer": "Beauty Labs SRL",
      "quantity":     "50ml",
      "ingredients":  "Aqua, Glycerin, Zinc Oxide, Titanium Dioxide, Tocopheryl Acetate",
      "lot_number":   "BL2026-03",
      "expiry_date":  "06.2028",
      "warnings":     "A nu se utiliza în apropierea ochilor."
    }'::jsonb,
    88,
    NOW() - INTERVAL '15 days', NOW() - INTERVAL '18 days', NOW() - INTERVAL '15 days'
) ON CONFLICT (id) DO NOTHING;

-- L3: needs_review electronics (low compliance score, missing CE mark)
INSERT INTO labels (id, workspace_id, created_by_user_id, product_id, status, image_s3_key, category, detected_language, fields_translated, compliance_score, missing_fields, created_at, updated_at)
VALUES (
    '$L3', '$WS_ID', '$U_OPS', '$P_ELEC',
    'needs_review', 'labels/$WS_ID/$L3/image.jpg', 'electronics', 'en',
    '{
      "product_name": "Cablu HDMI 4K Ultra HD 2m",
      "manufacturer": "TechConnect SRL",
      "quantity":     "1 buc",
      "warnings":     "A nu se lăsa la îndemâna copiilor mici."
    }'::jsonb,
    64,
    '[
      {"field": "lot_number",    "severity": "recommended"},
      {"field": "ce_mark",       "severity": "required"},
      {"field": "importer_info", "severity": "required"}
    ]'::jsonb,
    NOW() - INTERVAL '5 days', NOW() - INTERVAL '1 day'
) ON CONFLICT (id) DO NOTHING;

-- L4: processing (AI pipeline in progress)
INSERT INTO labels (id, workspace_id, created_by_user_id, product_id, status, image_s3_key, category, created_at, updated_at)
VALUES (
    '$L4', '$WS_ID', '$U_OPS', '$P_FOOD',
    'processing', 'labels/$WS_ID/$L4/image.jpg', 'food',
    NOW() - INTERVAL '2 hours', NOW() - INTERVAL '1 hour'
) ON CONFLICT (id) DO NOTHING;

-- L5: pending (uploaded, pipeline not yet started)
INSERT INTO labels (id, workspace_id, created_by_user_id, status, image_s3_key, created_at, updated_at)
VALUES (
    '$L5', '$WS_ID', '$U_OPS',
    'pending', 'labels/$WS_ID/$L5/image.jpg',
    NOW() - INTERVAL '10 minutes', NOW() - INTERVAL '10 minutes'
) ON CONFLICT (id) DO NOTHING;
SQL
echo "  ✓ 5 labels: 2 confirmed, 1 needs_review (score 64), 1 processing, 1 pending"

# ─── label_db: audit log ──────────────────────────────────────────────────────
label <<SQL
INSERT INTO label_audit_log (label_id, user_id, action, metadata, created_at)
VALUES
  ('$L1', '$U_ADMIN', 'upload',       '{"provider":"anthropic"}'::jsonb,                                 NOW() - INTERVAL '25 days'),
  ('$L1', '$U_ADMIN', 'ai_processed', '{"provider":"anthropic","confidence":0.94}'::jsonb,               NOW() - INTERVAL '25 days' + INTERVAL '1 minute'),
  ('$L1', '$U_ADMIN', 'confirmed',    '{}'::jsonb,                                                       NOW() - INTERVAL '22 days'),
  ('$L1', '$U_OPS',   'printed',      '{"job_id":"$PJ1","copies":3}'::jsonb,                             NOW() - INTERVAL '20 days'),
  ('$L2', '$U_ADMIN', 'upload',       '{"provider":"anthropic"}'::jsonb,                                 NOW() - INTERVAL '18 days'),
  ('$L2', '$U_ADMIN', 'ai_processed', '{"provider":"anthropic","confidence":0.89}'::jsonb,               NOW() - INTERVAL '18 days' + INTERVAL '2 minutes'),
  ('$L2', '$U_ADMIN', 'field_edited', '{"changes":{"ingredients":"corrected INCI order"}}'::jsonb,       NOW() - INTERVAL '16 days'),
  ('$L2', '$U_ADMIN', 'confirmed',    '{}'::jsonb,                                                       NOW() - INTERVAL '15 days'),
  ('$L3', '$U_OPS',   'upload',       '{"provider":"anthropic"}'::jsonb,                                 NOW() - INTERVAL '5 days'),
  ('$L3', '$U_OPS',   'ai_processed', '{"provider":"anthropic","confidence":0.64}'::jsonb,               NOW() - INTERVAL '5 days' + INTERVAL '3 minutes'),
  ('$L4', '$U_OPS',   'upload',       '{}'::jsonb,                                                       NOW() - INTERVAL '2 hours'),
  ('$L5', '$U_OPS',   'upload',       '{}'::jsonb,                                                       NOW() - INTERVAL '10 minutes')
ON CONFLICT DO NOTHING;
SQL
echo "  ✓ 12 audit log entries"

# ─── label_db: print_jobs ─────────────────────────────────────────────────────
label <<SQL
INSERT INTO print_jobs (id, label_id, workspace_id, format, label_size, copies, status, pdf_s3_key, created_at, completed_at)
VALUES
  ('$PJ1', '$L1', '$WS_ID', 'pdf', '100x50', 3, 'ready',  'print/$WS_ID/$PJ1/label.pdf', NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
  ('$PJ2', '$L1', '$WS_ID', 'pdf', '100x50', 1, 'failed', NULL,                           NOW() - INTERVAL '21 days', NOW() - INTERVAL '21 days')
ON CONFLICT (id) DO NOTHING;
SQL
echo "  ✓ 2 print_jobs in label_db (ready, failed)"

# ─── agent_db ─────────────────────────────────────────────────────────────────
echo ""
echo "▸ agent_db"
agent <<SQL
INSERT INTO agent_configs (
    workspace_id,
    vision_provider,   vision_model,
    transl_provider,   transl_model,
    valid_provider,
    fallback_provider, fallback_model,
    updated_at, updated_by_user_id
) VALUES (
    '$WS_ID',
    'anthropic', 'claude-sonnet-4-6',
    'anthropic', 'claude-sonnet-4-6',
    'rules_engine',
    'ollama',    'llava:7b',
    NOW(), '$U_ADMIN'
) ON CONFLICT (workspace_id) DO NOTHING;

INSERT INTO agent_call_logs (
    workspace_id, label_id, agent_type,
    provider, model,
    tokens_input, tokens_output, cost_usd,
    latency_ms, success, error_message, called_at
) VALUES
  ('$WS_ID','$L1','vision',      'anthropic',    'claude-sonnet-4-6', 1240,  892, 0.003241, 3420, true,  NULL,                        NOW() - INTERVAL '25 days'),
  ('$WS_ID','$L1','translation', 'anthropic',    'claude-sonnet-4-6',  640,  310, 0.001180,  980, true,  NULL,                        NOW() - INTERVAL '25 days'),
  ('$WS_ID','$L1','validation',  'rules_engine', 'v1.0',                 0,    0, 0.000000,   12, true,  NULL,                        NOW() - INTERVAL '25 days'),
  ('$WS_ID','$L2','vision',      'anthropic',    'claude-sonnet-4-6', 1580, 1020, 0.004120, 4100, true,  NULL,                        NOW() - INTERVAL '18 days'),
  ('$WS_ID','$L2','translation', 'anthropic',    'claude-sonnet-4-6',  720,  410, 0.001530, 1240, true,  NULL,                        NOW() - INTERVAL '18 days'),
  ('$WS_ID','$L2','validation',  'rules_engine', 'v1.0',                 0,    0, 0.000000,   15, true,  NULL,                        NOW() - INTERVAL '18 days'),
  ('$WS_ID','$L3','vision',      'anthropic',    'claude-sonnet-4-6',    0,    0, 0.000000,  500, false, 'upstream timeout after 5s', NOW() - INTERVAL '5 days' - INTERVAL '1 hour'),
  ('$WS_ID','$L3','vision',      'anthropic',    'claude-sonnet-4-6', 1100,  620, 0.002460, 2980, true,  NULL,                        NOW() - INTERVAL '5 days'),
  ('$WS_ID','$L3','translation', 'anthropic',    'claude-sonnet-4-6',  480,  290, 0.001020,  870, true,  NULL,                        NOW() - INTERVAL '5 days'),
  ('$WS_ID','$L3','validation',  'rules_engine', 'v1.0',                 0,    0, 0.000000,   18, true,  NULL,                        NOW() - INTERVAL '5 days'),
  ('$WS_ID','$L4','vision',      'anthropic',    'claude-sonnet-4-6', 1380,  760, 0.003040, 3700, true,  NULL,                        NOW() - INTERVAL '1 hour')
ON CONFLICT DO NOTHING;
SQL
echo "  ✓ agent config (anthropic + rules_engine + ollama fallback)"
echo "  ✓ 11 call log entries  |  1 failed vision call  |  total cost ~\$0.021"

# ─── print_db ─────────────────────────────────────────────────────────────────
echo ""
echo "▸ print_db"
printdb <<SQL
INSERT INTO print_jobs (id, workspace_id, label_id, user_id, format, size, copies, status, pdf_s3_key, created_at, updated_at)
VALUES
  ('$PJ1', '$WS_ID', '$L1', '$U_OPS',   'pdf', '100x50', 3, 'ready',  'print/$WS_ID/$PJ1/label.pdf', NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
  ('$PJ2', '$WS_ID', '$L1', '$U_OPS',   'pdf', '100x50', 1, 'failed', NULL,                           NOW() - INTERVAL '21 days', NOW() - INTERVAL '21 days'),
  ('$PJ3', '$WS_ID', '$L2', '$U_ADMIN', 'pdf',  '62x29', 2, 'queued', NULL,                           NOW() - INTERVAL '30 minutes', NOW() - INTERVAL '30 minutes')
ON CONFLICT DO NOTHING;
SQL
echo "  ✓ 3 print jobs (ready, failed, queued)"

# ─── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Done."
echo ""
echo "  Workspace:  Demo Corp SRL"
echo "  Workspace ID: $WS_ID"
echo "  Plan: business  |  Quota: 12 / 500 used"
echo ""
echo "  Login (password: DevPass123!)"
echo "  ┌─────────────────────────────┬──────────┐"
echo "  │ admin@demo.com              │ admin    │"
echo "  │ operator@demo.com           │ operator │"
echo "  │ viewer@demo.com             │ viewer   │"
echo "  └─────────────────────────────┴──────────┘"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
